### ISSUE TITLE
[Fixup] ODBC Example - Downloads for IBM i Access Client Solutions lacks License

### ISSUE THREAD

**Issue by amacgillivray** [IBM/ibmi-oss-examples#176]
### What example(s) need improvement?
The ODBC example for the IBM i environment now points to ibmi-oss-docs ([here](https://ibmi-oss-docs.readthedocs.io/en/latest/odbc/installation.html#ibm-i)). That page states, 

> To get the driver, visit the IBM i Access Client Solutions page and select Downloads for IBM i Access Client Solutions. After logging in and redirected to the IBM I Access Client Solutions download page, ... 

Following those instructions, the user clicks the link: 

![image](https://user-images.githubusercontent.com/40438470/128405103-34645423-3e1e-4c46-bd97-bd306d2dd27b.png)

And is taken to the following page: 

![image](https://user-images.githubusercontent.com/40438470/128405245-530a7312-fdea-450c-aef0-2aacbf2f63d0.png)

Clicking "View License", the user is shown a modal and told that there is no license available for the `English [en]` language: 

![image](https://user-images.githubusercontent.com/40438470/128405452-402479e4-8721-40e8-b9e4-6c0eca151ec7.png)

### What improvement(s) could be made?
Clarify by adding license text, clarifying what the purpose of the agreement on that page is for, or removing the requirement for the user to agree to a license that is not available to read.

**Comment by kadler** [comment]
Thanks for the report. This should be fixed now, please re-open if there are still concerns.
