### ISSUE TITLE
Error installing on ibmi

### ISSUE THREAD

**Issue by serininformatica** [IBM/ibmi-oss-examples#19]
-bash-4.4$ npm install odbc  

> odbc@2.2.2 install /www/nodejs/odbc-test/node_modules/odbc
> node-gyp configure build

gmake: Entering directory '/www/nodejs/odbc-test/node_modules/odbc/build'
  CXX(target) Release/obj.target/odbc/src/odbc.o
In file included from ../src/odbc.cpp:19:0:
/www/nodejs/odbc-test/node_modules/node-addon-api/napi.h:5:22: fatal error: functional: No such file or directory
 #include <functional>
                      ^
compilation terminated.
gmake: *** [odbc.target.mk:133: Release/obj.target/odbc/src/odbc.o] Error 1
gmake: Leaving directory '/www/nodejs/odbc-test/node_modules/odbc/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System OS400 7.3
gyp ERR! command "/QOpenSys/pkgs/lib/nodejs12/bin/node" "/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /www/nodejs/odbc-test/node_modules/odbc
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN odbc-test@1.0.0 No description
npm WARN odbc-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! odbc@2.2.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the odbc@2.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/LUCA/.npm/_logs/2020-04-20T13_35_48_203Z-debug.log
-bash-4.4$

**Comment by ThePrez** [comment]
Thanks for reporting! Please open this issue up to the `odbc` repository at https://github.com/markdirish/node-odbc

**Comment by markdirish** [comment]
I remembered seeing a node-odbc issue in a non-node-odbc repo in my email, but thought it was BitBucket! Couldn't find it...

Anyways, resolved this issue this morning: https://github.com/markdirish/node-odbc/issues/76
