### ISSUE TITLE
Convert python dbtoxlsx example to use pyodbc rather than ibmdb2

### ISSUE THREAD

**Issue by abmusse** [IBM/ibmi-oss-examples#35]
Investigate using pyodbc for database access rather than ibmdb2.

**Comment by ThePrez** [comment]
The dbtoxlsx example as currently written is a good "works out of the box" solution for people who have no interest in coding or setting stuff up (they just want data in a spreadsheet).

Sadly, using ODBC adds more setup task and makes this example much less useful in a ready-to-use utility use case. 

Until we can make ODBC out-of-the-box ready, we should instead just make a second flavor of the example
