### ISSUE TITLE
Replace postgresql page with redirect to ibmi-oss-docs

### ISSUE THREAD

**Issue by abmusse** [IBM/ibmi-oss-examples#66]
Now that https://github.com/IBM/ibmi-oss-docs/pull/23 is merged and considering at least one known article (https://www.itjungle.com/2020/06/15/more-open-source-databases-coming-to-ibm-i/) links to this page we should probably replace the page with a link to the new location instead of just deleting it.

@kadler 

We should link to the [readthedocs](https://ibmi-oss-docs.readthedocs.io/en/latest/postgresql.html) webpage instead of the [markdown file](https://github.com/IBM/ibmi-oss-docs/blob/master/postgresql.md) right?

**Comment by kadler** [comment]
Yes, please link to readthedocs.
